### ISSUE TITLE
download of the trained model weight

### ISSUE THREAD

**Issue by qihuihu20** [nachiket92/PGP#20]
Thanks for your work!
I can't download the trained model weight via the link you offered because of the restrictions of  network permission. Could you offer other download channels. I will be infinitely grateful.

**Comment by foww-0001** [comment]
i have download the model, but the file is only 2M and it is not a torch weights. Can you check the link you offered?
@nachiket92

**Comment by foww-0001** [comment]
> i have download the model, but the file is only 2M and it is not a torch weights. Can you check the link you offered? @nachiket92

sorry, i make a mistake. The weights is correct. Thanks for your work.

**Comment by qihuihu20** [comment]
Glad you solved your problem. If it is allowed, could you send the trained model weight to my email: huqihui123@163.com? Thanks a lot. @foww-0001

**Comment by ntutangyun** [comment]
> > i have download the model, but the file is only 2M and it is not a torch weights. Can you check the link you offered? @nachiket92
> 
> sorry, i make a mistake. The weights is correct. Thanks for your work.

Hi foww, I have also downloaded the weight files, but somehow cannot load: 
below are the outputs I get: 
I'm not an expert. kindly help:
```
2022-10-13 15:59:56.942100: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-13 15:59:57.062413: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/tangyun/Desktop/Tools/anaconda3/envs/pgp/lib/python3.7/site-packages/cv2/../../lib64:
2022-10-13 15:59:57.062424: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-13 15:59:57.080015: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-13 15:59:57.609825: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/tangyun/Desktop/Tools/anaconda3/envs/pgp/lib/python3.7/site-packages/cv2/../../lib64:
2022-10-13 15:59:57.609868: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/tangyun/Desktop/Tools/anaconda3/envs/pgp/lib/python3.7/site-packages/cv2/../../lib64:
2022-10-13 15:59:57.609873: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-10-13 15:59:59,872	INFO worker.py:1518 -- Started a local Ray instance.
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 22.672 seconds.
======
Reverse indexing ...
Done reverse indexing in 5.5 seconds.
======
Traceback (most recent call last):
  File "evaluate.py", line 29, in <module>
    evaluator = Evaluator(cfg, args.data_root, args.data_dir, args.checkpoint)
  File "/home/tangyun/Desktop/perception_error_modeling_experiments/PGP/train_eval/evaluator.py", line 46, in __init__
    checkpoint = torch.load(checkpoint_path)
  File "/home/tangyun/Desktop/Tools/anaconda3/envs/pgp/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/tangyun/Desktop/Tools/anaconda3/envs/pgp/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

**Comment by ntutangyun** [comment]
hi @foww-0001 what pytorch version you have installed I wonder ? thanks...

I checked online and some suggested the `persistent_load function` error is due to the torch version. but I'm using the same version `1.7.1` as in the document.

**Comment by ntutangyun** [comment]
OK my mistake... the downloaded weight file is the `tar` file itself. DO NOT unzip it...
just use it after the `-w` flag will do:   `python evaluate.py ... -w PGP_lr-scheduler.tar`

**Comment by rain8bow** [comment]
> 好吧，我的错误......下载的权重文件就是文件本身。不要解压缩它...只需在标志之后使用它就可以了：`tar``-w``python evaluate.py ... -w PGP_lr-scheduler.tar`

I apologize for interrupting you, but I'm unable to access the link the author previously provided for downloading the model weights. However, I'm quite eager to reproduce this code, and I was wondering if you could kindly share the model weights you downloaded with me via email. I understand that this is a bit of a bold request, and I truly appreciate your understanding and assistance. My email address is [2710631827@qq.com](mailto:2710631827@qq.com). Thank you so much!

**Comment by zachytong** [comment]
Hi @rain8bow , you can find the weights file in the PGP I forked: https://github.com/zachytong/PGP : )
